version: '3.2'
services:
  valet:
    build:
      context: .
      args:
        PHP_VERSION: $PHP_VERSION
        DEV_USER: "$DEV_USER"
        DB_HOST: "$DB_HOST"
        DB_USER: "$DB_USER"
        DB_PASSWORD: "$DB_PASSWORD"
        MAGENTO_USERNAME: "$MAGENTO_USERNAME"
        MAGENTO_PASSWORD: "$MAGENTO_PASSWORD"
        MAGENTO_USER_EMAIL: "$MAGENTO_USER_EMAIL"
        MAGENTO_ADMIN_URL: "$MAGENTO_ADMIN_URL"
        MAGENTO_MODULE_VENDOR: "$MAGENTO_MODULE_VENDOR"
        GIT_REPO_VENDOR: "$GIT_REPO_VENDOR"
        MAGENTO_MARKETPLACE_USER: "$MAGENTO_MARKETPLACE_USER"
        MAGENTO_MARKETPLACE_PASS: "$MAGENTO_MARKETPLACE_PASS"
        DOMAIN_SUFFIX: "$DOMAIN_SUFFIX"
    image: wdm:${PHP_VERSION}
    container_name: wdm-${PHP_VERSION}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - type: bind
        source: $DOMAIN_PATH
        target: /home/$DEV_USER/domains
      - type: bind
        source: ./storage/valet/certificates
        target: /home/$DEV_USER/.valet/Certificates
      - type: bind
        source: ./storage/valet/log
        target: /home/$DEV_USER/.valet/Log
      - type: bind
        source: ./storage/valet/nginx
        target: /home/$DEV_USER/.valet/Nginx
    networks:
      wdm_net:
        ipv4_address: 172.18.19.200

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db-store:/var/lib/mysql
    networks:
      wdm_net:
        ipv4_address: 172.18.19.100
    tty: true
    stdin_open: true

volumes:
  db-store:

networks:
  wdm_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.19.0/24
